### ISSUE TITLE
The height of textView will never grow with its contentSize in XCode5 & iOS7

### ISSUE THREAD

**Issue by voicecho** [hanspinckaers/GrowingTextView#33]

**Comment by mglidden** [comment]
The contentSize in HPTextViewInternal never gets updated. I believe this is a bug in iOS7 – if you search the Apple developer forum for "uitextview content size" you'll find a handful of other posts with the same issue.

It's probably best to wait a while longer and hope the iOS bug gets fixed.

**Comment by alexdd55** [comment]
UITextView resizes now automatically, if you select "use autolayout" and constraints are set correctly.
Its kind of confusing in the beginning, but works for me.

I only tried it with a text that came from a webservice, i did not try it with typing... but maybe it helps anyway ;)

**Comment by shaikhtariq11** [comment]
alexdd55 can u please give me trick to do the same.

**Comment by alexdd55** [comment]
shaikhtariq11 
set the contraints so that the teh distance is set to an element about/before and after. like distance to the content view and maybe scrolling to "off" (depends on the usage you have). 
that helped me to elimate the problem with recalculating the size.
to set this properly you might need the the current version of xcode (DP6) all previous version are telling you problem with constraints verywhere and do not solve the problem properly.

i hope this will help a little bit with your issue :)

**Comment by shaikhtariq11** [comment]
from three side which is upper, left and right side i set fixed constraints(not for lower).  i had a problem with height constraints height is not increasing with its contents from xib only i don't want to code for that. or can u please send me the sample code at my email id i.e. shaikh.tariq11@gmail.com

**Comment by alexdd55** [comment]
don't set a height, because then it will be fixed in the height.
i can not provide any sample code, because its all done in the interface builder.
i just did a lot of try and error with constraints.

to be honest, the constraints thing is stil confuses me and sometimes i just reset all contraints and start from scratch du keep it clean.

**Comment by hanspinckaers** [comment]
This has been fixed now. Please test with the latest code.
